language: python
python:
  - "2.7"
before_script:
  - psql -c 'create database unicore_comments_test;' -U postgres
install:
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
script:
  - ./run_tests.sh
after_success:
  - coveralls

