"""stream metadata table

Revision ID: 1bd67c605fbe
Revises: 1c8ee76214e4
Create Date: 2015-04-12 16:42:23.668018

"""

# revision identifiers, used by Alembic.
revision = '1bd67c605fbe'
down_revision = '1c8ee76214e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_metadata',
    sa.Column('app_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('content_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('metadata', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.PrimaryKeyConstraint('app_uuid', 'content_uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_metadata')
    ### end Alembic commands ###
