"""banned_users table

Revision ID: 1c8ee76214e4
Revises: 2dff97787d0d
Create Date: 2015-04-10 17:15:55.345467

"""

# revision identifiers, used by Alembic.
revision = '1c8ee76214e4'
down_revision = '2dff97787d0d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('app_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'app_uuid')
    )
    op.create_index('banneduser_app_index', 'banned_users', ['app_uuid'], unique=False)
    op.create_index('banneduser_user_index', 'banned_users', ['user_uuid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('banneduser_user_index', table_name='banned_users')
    op.drop_index('banneduser_app_index', table_name='banned_users')
    op.drop_table('banned_users')
    ### end Alembic commands ###
