"""initial comments and flags tables

Revision ID: 2dff97787d0d
Revises: 
Create Date: 2015-03-27 16:43:53.216031

"""

# revision identifiers, used by Alembic.
revision = '2dff97787d0d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('content_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('app_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('comment', sa.Unicode(length=3000), nullable=False),
    sa.Column('user_name', sa.Unicode(length=255), nullable=False),
    sa.Column('submit_datetime', sa.DateTime(), nullable=False),
    sa.Column('content_type', sa.Unicode(length=255), nullable=False),
    sa.Column('content_title', sa.Unicode(length=255), nullable=False),
    sa.Column('content_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('locale', sa.Unicode(length=6), nullable=False),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('moderation_state', sa.Unicode(length=255), nullable=False),
    sa.Column('ip_address', sa.Unicode(length=15), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('comment_app_content_index', 'comments', ['app_uuid', 'content_uuid'], unique=False)
    op.create_index('comment_submit_datetime_index', 'comments', ['submit_datetime'], unique=False)
    op.create_index('comment_user_index', 'comments', ['user_uuid'], unique=False)
    op.create_table('flags',
    sa.Column('comment_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('user_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('app_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('submit_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_uuid'], ['comments.uuid'], ),
    sa.PrimaryKeyConstraint('comment_uuid', 'user_uuid')
    )
    op.create_index('flag_app_index', 'flags', ['app_uuid'], unique=False)
    op.create_index('flag_submit_datetime_index', 'flags', ['submit_datetime'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('flag_submit_datetime_index', table_name='flags')
    op.drop_index('flag_app_index', table_name='flags')
    op.drop_table('flags')
    op.drop_index('comment_user_index', table_name='comments')
    op.drop_index('comment_submit_datetime_index', table_name='comments')
    op.drop_index('comment_app_content_index', table_name='comments')
    op.drop_table('comments')
    ### end Alembic commands ###
